### ISSUE TITLE
Third party sharing option is missing in the payload of data agreements

### ISSUE THREAD

**Issue by MARZOOQUE** [decentralised-dataexchange/bb-consent-api#311]

**Comment by georgepadayatti** [comment]
@albinpa This field was missing in the OpenAPI specification, I have update spec to include it.

**Comment by georgepadayatti** [comment]
@MARZOOQUE Don't let this block your development, you can already integrate it against the field mentioned in the updated Open API specification. Once the change is live, the dashboard can still function without any changes.
