### ISSUE TITLE
List all organisation admin logs requires Timestamp in the response

### ISSUE THREAD

**Issue by MARZOOQUE** [decentralised-dataexchange/bb-consent-api#349]

**Comment by georgepadayatti** [comment]
@albinpa I have updated organisation admin log in OpenAPI specification to camelCase.

https://github.com/decentralised-dataexchange/bb-consent-docs/commit/8e0d7337fec1b53d31377ede76314d0cb18cb201

@MARZOOQUE FYI ☝🏼 All the path parameters, query parameters, request body, response body should be following camelCase syntax for fields.
