### ISSUE TITLE
Logo image and Cover image is giving 401

### ISSUE THREAD

**Issue by josmilan** [decentralised-dataexchange/bb-consent-api#360]
With service scope, not able to load the image. The response is 401.

On the client side, the API key is already passing. Do we need to pass an extra header?

**Comment by georgepadayatti** [comment]
@albinpa Can you check this and get back ?

**Comment by albinpa** [comment]
Yes.

**Comment by josmilan** [comment]
Images are not getting loaded

**Comment by georgepadayatti** [comment]
@josmilan `individualId` has to be passed the header.

![2023-10-26_19-44_1](https://github.com/decentralised-dataexchange/bb-consent-api/assets/16397960/7fd28d8f-4719-441a-879e-baf08fe61a18)
