### ISSUE TITLE
Question: Log handling

### ISSUE THREAD

**Issue by lalc** [decentralised-dataexchange/bb-consent-api#451]
Could we log all HTTP requests? @georgepadayatti 

Now, the logs seem to show only the security log providing login info and its pretty empty.

**Comment by georgepadayatti** [comment]
Yes will take a note.

**Comment by georgepadayatti** [comment]
> l HTTP requests? @georgepadayatti

Should we log all the API calls (onboard, config, service and audit) or just those of organisation admin ?

**Comment by lalc** [comment]
Do you know if all calls could be logged? What do you suggest? Is it possible to switch ON and OFF? E.g. userlogs are something we need to enable. But all admin actions shall be.

**Comment by georgepadayatti** [comment]
> All calls could be logged. What do you suggest? Is it possible to switch ON and OFF? E.g. userlogs are something we need to enable. But all admin actions shall be.

Maybe add configuration field for it ?

**Comment by lalc** [comment]
Sounds good
