### ISSUE TITLE
Create draft data agreement with version 1.0.0

### ISSUE THREAD

**Issue by albinpa** [decentralised-dataexchange/bb-consent-api#460]
- [ ] On creating draft data agreement the version should be 1.0.0
- [ ] On updating a published data agreement as draft, the version should increment.

**Comment by georgepadayatti** [comment]
> * [ ]  On creating draft data agreement the version should be 1.0.0
> * [ ]  On updating a published data agreement as draft, the version should increment.

What happens in the following scenario:

1. Organisation admin created data agreement Marketing and campaign as draft
2. Decided to update it and again save it as draft

Will the version increment ?

**Comment by georgepadayatti** [comment]
> * [ ]  On creating draft data agreement the version should be 1.0.0
> * [ ]  On updating a published data agreement as draft, the version should increment.

What happens in the following scenario:

1. Organisation admin created data agreement Marketing and campaign as published. The current version is 1.0.0
2. Decided to update it and again save it as draft. 

What will be version now ?

**Comment by albinpa** [comment]
Yes, the version will not increment. The Marketing and campaign will be version 2.0.0
