### ISSUE TITLE
Version number for draft data agreements

### ISSUE THREAD

**Issue by albinpa** [decentralised-dataexchange/bb-consent-api#461]
Changes to be made

- [ ] https://github.com/decentralised-dataexchange/bb-consent-api/issues/460
- [ ] If the existing data agreement is published and then updated as a draft, then the version should increment.

**Comment by georgepadayatti** [comment]
Reference image: 

![2023-11-06_16-52](https://github.com/decentralised-dataexchange/bb-consent-api/assets/16397960/8c743746-b576-422e-bb31-7ad3d22f70d5)
