### ISSUE TITLE
Consent Records

### ISSUE THREAD

**Issue by georgepadayatti** [decentralised-dataexchange/bb-consent-api#465]
1. Organisation admin created a data agreement with consent lawful basis of processing and published it towards individuals.
2. Individual viewed the data agreement from privacy dashboard and decided to opt-in
3. Organisation admin updated the data agreement and published it. Now the version of the data agreement is 2.0.0
4. Individual viewed the data agreement from privacy dashboard and decided to opt-out
5. Organisation admin from consent records page, should be able to 2 consent record of same id but with different agreement events.

At present the above is not the case, it is only posssible to view the latest event.

**Comment by lalc** [comment]
Great case! Awesome!

**Comment by georgepadayatti** [comment]
- [ ] In audit - LIST - Fetch all consent records endpoint should return all the consent records by query through revisions.
![2023-11-07_18-16](https://github.com/decentralised-dataexchange/bb-consent-api/assets/16397960/ed3be91e-3b4b-4fb3-ada7-2c899964c2aa)

- [ ] Sort by timestamp (please double check to make sure it works properly)
- [ ] At present the endpoint response contains the following response
```
 "dataAgreement": {
              "purpose": "Passport Verification for tests",
              "lawfulBasis": "vital_interest"
          }
```

1. Both `purpose` and `lawfulBasis` should be purpose of a specific data agreement revision to which this consent record belongs to.
2. Add a version field which will be version of the specific data agreement revision.

4. La

**Comment by georgepadayatti** [comment]
Known issue:

1. Organisation admin created a Marketing and campaign (consent lawful basis) data agreement and published it.
2. John doe opened the privacy dashboard and decided to opt-in
3. Organisation admin edited Marketing and campaign and published it again.
4. John doe opened the privacy dashboard and decided to opt-out.


Now there will to consent records against 2 different data agreement revisions. one for 1.0.0 and other for 2.0.0
