### ISSUE TITLE
Fetch individual - able to fetch individual details with another individual id in header

### ISSUE THREAD

**Issue by josmilan** [decentralised-dataexchange/bb-consent-api#473]
We are able to send the request with "X-ConsentBB-IndividualId" header as a different individual id

cURL request

curl --location 'https://staging-consent-bb-api.igrant.io/v2/service/individual/6549bd13ff470577e0f3d3f8' \
--header 'Accept: application/json' \
--header 'X-ConsentBB-IndividualId: 65366979db611cb1948aca50' \
--header 'Authorization: ApiKey eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTY29wZXMiOlsic2VydmljZSJdLCJPcmdhbmlzYXRpb25JZCI6IjY1MjY1Nzk2OTM4MGYzNWZhMWMzMDI0NSIsIk9yZ2FuaXNhdGlvbkFkbWluSWQiOiI2NTI2NTc5NjkzODBmMzVmYTFjMzAyNDMiLCJleHAiOjE3MDA2NTYxMzJ9.BIfpLGSQTr4IQW1OMuIelS5TnOhvPiz3umtnSKaVpeo'

check the **path parameter** and header **X-ConsentBB-IndividualId**

Same above for all the individual APIs

**Comment by georgepadayatti** [comment]
@josmilan This is the intended behaviour. But if there is any further comments feel free to discuss in this thread or slack channel.
