### ISSUE TITLE
Purge logs endpoint

### ISSUE THREAD

**Issue by georgepadayatti** [decentralised-dataexchange/bb-consent-api#558]
- [ ] Purge all logs except last 100 logs.

**Comment by albinpa** [comment]
@georgepadayatti Is this endpoint ok, "/v2/audit/admin/logs/purge" ?

**Comment by georgepadayatti** [comment]
> @georgepadayatti Is this endpoint ok, "/v2/audit/admin/logs/purge" ?

`/v2/config/logs/purge`
