### ISSUE TITLE
On updating DA with Attribute, save as draft. The existing DA in privacy dashboard, will update with Attribute name 

### ISSUE THREAD

**Issue by kashishmalik** [decentralised-dataexchange/bb-consent-api#574]
On updating DA with Attribute, save as draft. The existing DA in privacy dashboard, will update with Attribute name

**Comment by albinpa** [comment]
On updating DA with Attribute, save as draft. The list active data agreements api in service will return the latest published version as always, it won't return the draft version.

**Comment by georgepadayatti** [comment]
Can you also make sure READ - Read data agreement (`/service/data-agreement/{dataAgreementId}`) also returns the active data agreement ?
