### ISSUE TITLE
Perform validation against OpenAPI spec

### ISSUE THREAD

**Issue by georgepadayatti** [decentralised-dataexchange/bb-consent-api#592]
1. Follow the instructions as mentioned [here](https://github.com/decentralised-dataexchange/bb-consent-playground#steps-to-run-bdd-tests) to setup a test environment.
2. Use postman to execute API calls and check if there is discrepancies against [GovStack Open API specification](https://github.com/GovStackWorkingGroup/bb-consent/blob/main/api/consent-openapi.yaml)

Misalignments are fixed in the following issues:

- [x] https://github.com/decentralised-dataexchange/bb-consent-api/issues/594
- [x] https://github.com/decentralised-dataexchange/bb-consent-api/issues/612
- [x] https://github.com/decentralised-dataexchange/bb-consent-api/issues/614
- [x] https://github.com/decentralised-dataexchange/bb-consent-api/issues/616

**Comment by georgepadayatti** [comment]
Some observations upon performing API validation:

- [ ] Data agreement is missing DPIA field (this is not dpia summary or dpia URL field)

**Comment by albinpa** [comment]
- [ ] Id and version field in request body is mandatory for creating and updating policy in consent bb swagger specification

**Comment by albinpa** [comment]
- [ ] `GET /config/policy/{policyId}/revisions/` consent bb swagger specification response contains only policy object and doesn't contain revisions array

**Comment by albinpa** [comment]
Revisions

- [ ] `successorId` is implemented whereas in consent bb swagger specification its `successor`.
- [ ] `authorizedByOtherId` is implemented whereas in consent bb swagger specification its `authorisedByOther`.
- [ ] `authorizedByIndividualId` is implemented whereas in consent bb swagger specification its `authorizedByIndividual` object
`"authorizedByIndividual": {
      "id": "",
      "externalId": "",
      "externalIdType": "",
      "identityProviderId": ""
    }`
    [https://github.com/GovStackWorkingGroup/bb-consent/blob/3f7d2e2fa2b55b1f36890bfc20316227c9ee98ca/api/consent-openapi.yaml#L2292C6-L2292C6](url)

**Comment by albinpa** [comment]
- [ ] `id` and `version` field in request body is mandatory for creating and updating data agreement in consent bb swagger specification
[https://github.com/GovStackWorkingGroup/bb-consent/blob/3f7d2e2fa2b55b1f36890bfc20316227c9ee98ca/api/consent-openapi.yaml#L2040](url)
- [ ] `lifecycle` string field is implemented whereas in consent bb swagger specification it's object with the following values
`"lifecycle": {
        "id": "",
        "name": ""
      }`
      [https://github.com/GovStackWorkingGroup/bb-consent/blob/3f7d2e2fa2b55b1f36890bfc20316227c9ee98ca/api/consent-openapi.yaml#L2508](url)
- [ ]  `dataUse` field is missing
- [ ] `dpia` field is missing
- [ ] `compactibleWithVersionId` is implemented whereas in consent bb swagger specification it's  `compactableWithVersion`
- [ ] controller is an object in consent bb swagger specification
https://github.com/GovStackWorkingGroup/bb-consent/blob/3f7d2e2fa2b55b1f36890bfc20316227c9ee98ca/api/consent-openapi.yaml#L2377-L2404

**Comment by albinpa** [comment]
Individual

- [ ] `id ` field in request body is mandatory for creating and updating individual in consent bb swagger specification
https://github.com/GovStackWorkingGroup/bb-consent/blob/3f7d2e2fa2b55b1f36890bfc20316227c9ee98ca/api/consent-openapi.yaml#L2006-L2037

**Comment by albinpa** [comment]
Webhook

- [ ] id field in request body is mandatory for creating and updating webhook in consent bb swagger specification
https://github.com/GovStackWorkingGroup/bb-consent/blob/3f7d2e2fa2b55b1f36890bfc20316227c9ee98ca/api/consent-openapi.yaml#L2531-L2572

- [ ] `revisionId` is present in read and list webhook endpoints in consent bb swagger specification
https://github.com/GovStackWorkingGroup/bb-consent/blob/3f7d2e2fa2b55b1f36890bfc20316227c9ee98ca/api/consent-openapi.yaml#L735-L776

**Comment by albinpa** [comment]
Consent Record

- [ ] `consentRecord` which is implemented is different from consent bb swagger specification
` "consentRecord": {
       "id": "656ef40ea457a5ffa7233b8b",
       "dataAgreementId": "656ee8a7a457a5ffa7233b72",
       "dataAgreementRevisionId": "656ee8a7a457a5ffa7233b76",
       "dataAgreementRevisionHash": "5eb8f4370a85f165a0dc0f1a7d2f04266340c04c",
       "individualId": "656eebc7a457a5ffa7233b7f",
       "optIn": true,
       "state": "unsigned",
       "signatureId": ""
   }
`
https://github.com/GovStackWorkingGroup/bb-consent/blob/3f7d2e2fa2b55b1f36890bfc20316227c9ee98ca/api/consent-openapi.yaml#L2236-L2289

**Comment by albinpa** [comment]
Create consent record

- [ ] Individual id supplied as http header, open api spec passes individualid as query param
https://github.com/GovStackWorkingGroup/bb-consent/blob/3f7d2e2fa2b55b1f36890bfc20316227c9ee98ca/api/consent-openapi.yaml#L1333-L1384
Update consent record

- [ ] Uses `dataagreementId` and `individualId` as queryparams and request body contains only `optIn` field whereas consent bb swagger specification contains whole consent record object as request body
https://github.com/GovStackWorkingGroup/bb-consent/blob/3f7d2e2fa2b55b1f36890bfc20316227c9ee98ca/api/consent-openapi.yaml#L1584-L1634

**Comment by georgepadayatti** [comment]
> * [ ]  `GET /config/policy/{policyId}/revisions/` consent bb swagger specification response contains only policy object and doesn't contain revisions array
>   https://github.com/GovStackWorkingGroup/bb-consent/blob/3f7d2e2fa2b55b1f36890bfc20316227c9ee98ca/api/consent-openapi.yaml#L214

@georgepadayatti Revisions endpoint is returning a single policy object rather revisions. This is an issue that should be rectified from GovStack end.

**Comment by georgepadayatti** [comment]
> Webhook
> 
> * [ ]  id field in request body is mandatory for creating and updating webhook in consent bb swagger specification
>   https://github.com/GovStackWorkingGroup/bb-consent/blob/3f7d2e2fa2b55b1f36890bfc20316227c9ee98ca/api/consent-openapi.yaml#L2531-L2572
> * [ ]  `revisionId` is present in read and list webhook endpoints in consent bb swagger specification
>   https://github.com/GovStackWorkingGroup/bb-consent/blob/3f7d2e2fa2b55b1f36890bfc20316227c9ee98ca/api/consent-openapi.yaml#L735-L776

@georgepadayatti Point 2, webhooks doesn't support revisions, so there is no point in having `revisionId` as query params

**Comment by georgepadayatti** [comment]
> * consent

authorizedByOther will stay as is.

**Comment by georgepadayatti** [comment]
@albinpa Some comments after discussion with GovStack: 

- GovStack follows US english so 'z' will be retained in the fields instead of 's'.
- Review signature workflow in Consent Records:

> 1. When a consent record is updated, it invalidates the signature
> 2. Then signature needs to be prepared using create signature endpoint.
> 3. Then signature can updated in consent record using update signature endpoint.

**Comment by georgepadayatti** [comment]
> > * [ ]   `GET /config/policy/{policyId}/revisions/` consent bb swagger specification response contains only policy object and doesn't contain revisions array
> >   https://github.com/GovStackWorkingGroup/bb-consent/blob/3f7d2e2fa2b55b1f36890bfc20316227c9ee98ca/api/consent-openapi.yaml#L214
> 
> @georgepadayatti Revisions endpoint is returning a single policy object rather revisions. This is an issue that should be rectified from GovStack end.

@albinpa As discussed, conveyed this to GovStack, they will rectify the 2nd point on their end.

**Comment by georgepadayatti** [comment]
> Create consent record
> 
> * [ ]  Individual id supplied as http header, open api spec passes individualid as query param
>   https://github.com/GovStackWorkingGroup/bb-consent/blob/3f7d2e2fa2b55b1f36890bfc20316227c9ee98ca/api/consent-openapi.yaml#L1333-L1384
> 
> Update consent record
> 
> * [ ]  Uses `dataagreementId` and `individualId` as queryparams and request body contains only `optIn` field whereas consent bb swagger specification contains whole consent record object as request body
> 
> https://github.com/GovStackWorkingGroup/bb-consent/blob/3f7d2e2fa2b55b1f36890bfc20316227c9ee98ca/api/consent-openapi.yaml#L1584-L1634

Both points will be rectified on their end.

**Comment by georgepadayatti** [comment]
> Consent Record
> 
> * [ ]  `consentRecord` which is implemented is different from consent bb swagger specification
>   `"consentRecord": { "id": "656ef40ea457a5ffa7233b8b", "dataAgreementId": "656ee8a7a457a5ffa7233b72", "dataAgreementRevisionId": "656ee8a7a457a5ffa7233b76", "dataAgreementRevisionHash": "5eb8f4370a85f165a0dc0f1a7d2f04266340c04c", "individualId": "656eebc7a457a5ffa7233b7f", "optIn": true, "state": "unsigned", "signatureId": "" }`
>   https://github.com/GovStackWorkingGroup/bb-consent/blob/3f7d2e2fa2b55b1f36890bfc20316227c9ee98ca/api/consent-openapi.yaml#L2236-L2289

@albinpa As discussed, conveyed this to GovStack, they will rectify on their end.

**Comment by georgepadayatti** [comment]
> * [ ]  `id` and `version` field in request body is mandatory for creating and updating data agreement in consent bb swagger specification
>   [https://github.com/GovStackWorkingGroup/bb-consent/blob/3f7d2e2fa2b55b1f36890bfc20316227c9ee98ca/api/consent-openapi.yaml#L2040](url)
> * [ ]  `lifecycle` string field is implemented whereas in consent bb swagger specification it's object with the following values
>   `"lifecycle": { "id": "", "name": "" }`
>   [https://github.com/GovStackWorkingGroup/bb-consent/blob/3f7d2e2fa2b55b1f36890bfc20316227c9ee98ca/api/consent-openapi.yaml#L2508](url)
> * [ ]   `dataUse` field is missing
> * [ ]  `dpia` field is missing
> * [ ]  `compactibleWithVersionId` is implemented whereas in consent bb swagger specification it's  `compactableWithVersion`
> * [ ]  controller is an object in consent bb swagger specification
>   https://github.com/GovStackWorkingGroup/bb-consent/blob/3f7d2e2fa2b55b1f36890bfc20316227c9ee98ca/api/consent-openapi.yaml#L2377-L2404

All should be supported except lifecycle as it can be a string.

**Comment by georgepadayatti** [comment]
> Revisions
> 
> * [ ]  `successorId` is implemented whereas in consent bb swagger specification its `successor`.
> * [ ]  `authorizedByOtherId` is implemented whereas in consent bb swagger specification its `authorisedByOther`.
> * [ ]  `authorizedByIndividualId` is implemented whereas in consent bb swagger specification its `authorizedByIndividual` object
>   `"authorizedByIndividual": { "id": "", "externalId": "", "externalIdType": "", "identityProviderId": "" }`
> 
> https://github.com/GovStackWorkingGroup/bb-consent/blob/3f7d2e2fa2b55b1f36890bfc20316227c9ee98ca/api/consent-openapi.yaml#L2292C6-L2292C6

All points will be recitifed on GovStack end, except `authorizedByOther`, it should not have `Id` suffix
