### ISSUE TITLE
Revisions

### ISSUE THREAD

**Issue by albinpa** [decentralised-dataexchange/bb-consent-api#612]
### Changes to align with GovStack OpenAPI specification

- [x] `authorizedByOtherId` needs to be changed to `authorizedByOther`
- [x] `schemaName` should start in capital letter eg. now we have `schemaName` as `dataAgreement`, it should be `DataAgreement`
- [x] Remove 3 extra fields - `id`, `predecessorHash` and `predecessorSignature` in `serializedSnapshot`

### Solution

1. All the above changes will be made.
2. Migration function would be written to update `authorizedByOther` and value of `schemaName` fields for older records. Value of `serializedSnapshot` will remain the same for older records.

Note: Do make sure all the impacted APIs are working as intended and doesn't crash the application.

This issue is related to #592

**Comment by georgepadayatti** [comment]
Is this the change you are attempting fix here ? https://github.com/decentralised-dataexchange/bb-consent-api/issues/592#issuecomment-1856162384

**Comment by georgepadayatti** [comment]
> `serializedSnapshot` should not contain `id`,`serializedSnapshot`,`serializedHash`,`successorId`,`predessorHash`,`predecessorSignature`.Now it contains `id`,`predessorHash`,`predecessorSignature`

What does this mean ? Are you trying to say serializedSnapshot is missing some fields and we need to add them ?

**Comment by albinpa** [comment]
> > `serializedSnapshot` should not contain `id`,`serializedSnapshot`,`serializedHash`,`successorId`,`predessorHash`,`predecessorSignature`.Now it contains `id`,`predessorHash`,`predecessorSignature`
> 
> What does this mean ? Are you trying to say serializedSnapshot is missing some fields and we need to add them ?

Now the serializedSnapshot contains `id`,`predessorHash`,`predecessorSignature` as in our govstack swagger spec.
![image](https://github.com/decentralised-dataexchange/bb-consent-api/assets/99476802/8c3c322c-1020-4a32-84e4-a720687f0721)
In govstack swagger spec , `serializedSnapshot` does not contain `id`,`serializedSnapshot`,`serializedHash`,`successorId`,`predessorHash`,`predecessorSignature`

![image](https://github.com/decentralised-dataexchange/bb-consent-api/assets/99476802/e0c71671-4c97-4618-ac7a-196ab5fd19bb)
