### ISSUE TITLE
Review signature workflow in Consent Records

### ISSUE THREAD

**Issue by albinpa** [decentralised-dataexchange/bb-consent-api#616]
Verify if the following is true and if not make the necessary changes:

1. When a consent record is updated, it invalidates the signature
2. Then signature needs to be prepared using create signature endpoint.
3. Then signature can updated in consent record using update signature endpoint.

Only type of signatures supported will be ES256 signatures.

This issue is related to #592

- [x] Add `consentRecord` and `revision` objects to the response of update signature endpoint

**Comment by georgepadayatti** [comment]
Acceptance criteria for this issue: [link](https://github.com/decentralised-dataexchange/bb-consent-playground/blob/main/gherkin/features/issue_616/issue_616.feature)

Could you implement the steps for validating the above criteria against the fix/feature branch?
